### ISSUE TITLE
How to build for android with com.android.tools.build:gradle:3.0.1

### ISSUE THREAD

**Issue by angelos3lex** [agenthunt/react-native-mailcore#7]
Could you please guide me (also update docs) about how we can build react-native-mailcore for android using android tools version  com.android.tools.build:gradle:3.0.1?
I followed the instructions using both other options but i face following error:
 > What went wrong:
Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lcom/reactlibrary/BuildConfig;

**Comment by angelos3lex** [comment]
Ok, i got it running, by changing 
>minSdkVersion  21 

from 

>minSdkVersion 19 

too, and adding 
>multiDexEnabled true 

to defaultConfig in app/build.gradle.. 
Also, i used the:
```
packagingOptions{
        pickFirst '**/libgnustl_shared.so'
    }
``` 
as mentioned in docs for version tools for gradle version 2.3.3.
The problem is, that app crashes when i try to send email using my credentials through gmail smtp.
Also, I do not get any logs by the catch method, just crashing.
Tested on Android 6.0 API 23 only.
Any ideas @agenthunt ?

**Comment by agenthunt** [comment]
Ok. Great.
Does android log cat give more info about crash?

**Comment by angelos3lex** [comment]
@agenthunt ok found a way, this is the error i get:
> 09-06 10:29:25.508 4434-4434/com.inkotrack E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.inkotrack, PID: 4434
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.inkotrack-2/lib/x86/libMailCore.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
        at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
        at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:14)
        at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
        at com.reactlibrary.RNMailCoreModule$1.run(RNMailCoreModule.java:42)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by angelos3lex** [comment]
@agenthunt When i run the example app, it works fine, though if i change example app to targetSdkVersion 23 from targetSdkVersion 22, it crashes with same error. In my app, when i downgrade from targetSdkVersion 25 to 22, i face the following error in android logcat:
>java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.inkotrack-2/lib/x86/libMailCore.so"...
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
        at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
        at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
        at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:14)
        at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
        at com.reactlibrary.RNMailCoreModule$1.run(RNMailCoreModule.java:41)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mcavaliere** [comment]
@agenthunt Ping on this. Happening with a client app (Expo 30, ejected to ExpoKit), so looking for good workarounds.

**Comment by anagar23** [comment]
I also got a crash on Android with Gradle 3.0.1 version

logs:

```
11-14 15:30:59.300 11360-11360/com.elth E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.elth, PID: 11360
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZSt24__throw_out_of_range_fmtPKcz" referenced by "/data/app/com.elth-1/lib/arm/libMailCore.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:977)
        at java.lang.System.loadLibrary(System.java:1530)
        at com.libmailcore.MainThreadUtils.<init>(MainThreadUtils.java:19)
        at com.libmailcore.MainThreadUtils.<clinit>(MainThreadUtils.java:9)
        at com.libmailcore.MainThreadUtils.singleton(MainThreadUtils.java:14)
        at com.libmailcore.NativeObject.<clinit>(NativeObject.java:42)
        at com.reactlibrary.RNMailCoreModule$1.run(RNMailCoreModule.java:42)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

**Comment by angelos3lex** [comment]
@anagar23 that's where i also couldn't find solution and made new bridge  [here](https://github.com/angelos3lex/react-native-smtp-mailer)

**Comment by alexiskattan** [comment]
@angelos3lex thank you for the smtp lib! do you know if there is a react native one for imap also?

**Comment by gerard-payne** [comment]
> Ok, i got it running keeping gradle version 3.0.1, by changing
> 
> > minSdkVersion  19
> 
> to
> 
> > minSdkVersion 21
> 
> and adding
> 
> > multiDexEnabled true
> 
> to defaultConfig in app/build.gradle.. Also, i used the:
> 
> ```
> packagingOptions{
>         pickFirst '**/libgnustl_shared.so'
>     }
> ```
> 
> as mentioned in docs for version tools for gradle version 2.3.3. The problem is, that app crashes when i try to send email using my credentials through gmail smtp. Also, I do not get any logs by the catch method, just crashing. Tested on Android 6.0 API 23 only. Any ideas @agenthunt ?

I'm having trouble with the latest version of react-native force quitting with loginImap.
The above no longer works.

```
library might be using APIs not available in 19    
        Suggestion: use a compatible library with a minSdk of at most 19,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react.flipper" to force usage (may lead to runtime failures) 
```
